@startuml
note "Tous les attributs sont NOT NULL par défaut" as note




class Utilisateur{
  <primary> email : str
  password : str (hash)
  nom : str
  prenom : str
  tel : str
  creation_date : datetime
  is_active : int
}
note right
  constraint 0<=is_active<=1
end note

class Administrateur{
}

class Candidat{
}
class Recruteur{
}



class Type_Organisation{
  <primary> name : str
}

class Organisation{
  <primary> siret : int
  name : str
  adresse : str
}

class Etat{
  <primary> id : int
  description : text
}

class Offre{
  <primary> id : int
  valid_date : datetime
  indications : text
}

class Fiche_de_poste{
  <primary> id : int
  intitule : str
  rythme_travail : float
  salaire_min : float
  salaire_max : float
  description : str
}

class Status_de_poste{
  <primary> id : int
  status : str
  responsable_hierarchique : str
}
class Type_metier{
  <primary> id : int
  type : str
}

class Lieu{
  <primary> id : int
  numero_rue : int
  rue : str
  ville : str
  postcode : str 
}

class Candidature{
  <primary> id : int
  date_candidature : str

}

class Pieces_dossier{
  <primary> id : int
}

class CV{}
class cover_letter{}
class IDCard{}
class Photo{}
class Diplome{}

CV -|> Pieces_dossier
cover_letter -|> Pieces_dossier
IDCard -|> Pieces_dossier
Photo -|> Pieces_dossier
Diplome -|> Pieces_dossier

Candidature "*" -- "1" Candidat : "Modifier la candidature"
Candidature "*" -- "1" Offre
Candidature "1" -- "*" Pieces_dossier
Offre "1" -- "1" Etat
Administrateur -|> Utilisateur
Recruteur -|> Utilisateur
Candidat -|> Utilisateur
Organisation "1" -- "1" Type_Organisation
Organisation "1" -- "1" Fiche_de_poste
Fiche_de_poste "1" -- "*" Offre 
Fiche_de_poste "1" -- "1" Status_de_poste 
Fiche_de_poste "1" -- "1" Lieu 
Fiche_de_poste "*" -- "1 *" Recruteur : "Créer, modifier ou alonger la date de validité"


@enduml