@startuml



left to right direction
rectangle Fonctionnalitées {
"Accepter ou refuser une candidature" as (f1)
"Poster une offre" as (f2)
"Visualiser les offres" as (f3)
"se connecter" as (f4)
"inscription" as (f7)
"Accepter ou refuser de nouveaux administrateurs" as (f5)
"Demander à devenir administrateur" as (f6)
"vérifier la validité du mot de passe" as (f8)
"Voir les nouvelles demandes d'administration" as (f9)
"Candidater" as (f10)
"Se déconnecter" as (f11)
"Visualiser les candidatures valides" as (f12)
"Modifier ou supprimer une offre" as (f13)
"Valider ou refuser demande d'enregistrement d'une organisation" as (f14)
"Visualiser demande d'enregistrement d'une organisation" as (f22)
"Visualiser une demande de rejoindre une organisation en tant que recruteur" as (f15)
"Valider ou refuser une demande de rejoindre une organisation en tant que recruteur" as (f16)
"Demander à rejoindre une organisation en tant que recruteur" as (f17)
"Visualiser ses candidatures " as (f18)
"Modifier ou supprimer ses candidatures " as (f19)



(f4) ..> (f7) : extends
(f7) .> (f8) : includes
(f9) .> (f5) : extends
(f3) .> (f10) :extends
(f12) .> (f1) : extends
(f15) .> (f16) : extends
(f18) .> (f19) : extends
(f22) .> (f14) : extends


}
:Administrateur: --> (f9)
:Administrateur: --> (f22)
:Administrateur: --> (f15)
:Recruteur: --> (f2)
:Recruteur: --> (f12)
:Recruteur: --> (f13)
:Candidat: --> (f6)
:Candidat: --> (f3)
:Candidat: --> (f11)
:Candidat: --> (f17)
:Candidat: --> (f18)
:Utilisateur non connecté: --> (f7)
:Utilisateur non connecté: --> (f4)


@enduml
